### ISSUE TITLE
Add time point rank

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaTime#1]
Create function named `addRank` that checks the rank of a given `colData` field within each subject.

In practice, we will often use this to rank time points within a given subject.

Use the function `rank` and provide the same function arguments. In addition, arguments must specify the colData field used for ranking, and the name for the newly added field. These arguments can have similar names than we use in **mia** functions e.g. `transformSamples`.

Start with something simple and we can discuss the details in review phase.

**Comment by YagmurSimsekk** [comment]
I have added to addRank.R to devel branch but i am not really sure if i am on the right track.

**Comment by antagomir** [comment]
make PR and we see

**Comment by YagmurSimsekk** [comment]
PR is added
