### ISSUE TITLE
Distance from baseline sample

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaTime#11]
Time series analyses often measure dissimilarity (beta distance) from baseline. In this case, beta diversity needs to be calculated  between all other samples against a given reference sample, for instance baseline time point. This speeds up beta diversity calculation.

Suggestion: let's implement a function that calculates beta diversity between all samples vs. a given reference sample (specified by sample name). This must have access to all beta diversity measures available in *mia*. The output dissimilarities can be stored to colData (one dissimilarity from the reference sample per colData sample).

The examples would then show how to identify baseline sample (sample with time=0 or minimum time point), and then how to apply this function to add the beta diversities.

Suitable function name (to start with at least): `calculateDivergenceFromBaseline`.

**Comment by antagomir** [comment]
For demo purposes, one can pick a single subject (`se` subset) from the hitchip1006 data to keep things simple.

**Comment by antagomir** [comment]
I just realized that this can be achieved with the But: I just noticed that this can be achived via `mia::estimateDivergence`. 

I will close this one, and open a new issue that is related but different.

**Comment by microsud** [comment]
The divergence function in Mia is not the same as calculating divergence from starting sample. SyncomR has three options. Compared to starting Composition i.e. divergence, compared to each consecutive time point i.e. succession and compared to last sample i.e. convergence. These have different information about the system.

**Comment by antagomir** [comment]
It is not the same but divergence from baseline is easily calculated with `mia::estimateDivergence` by using the baseline sample as the reference. I have now added an example in the vignette in PR #14  - other time steps divergences require a different approach because the "reference" sample is not constant. 

It is a good idea to call the consecutive time point differences "succession" to keep in sync with common terminology. But should we use this if the time interval is more than one step? I think yes. The time step is just a parameter, the main idea is the same.

"Convergence" can be calculated in a same way than "divergence", with `mia::estimateDivergence`. I will add this to the vignette PR #14 as well. I am not sure if there would be added value to creating a function that calculates distance from baseline, and distance from last time point, when we can readily use the mia function. 

However, it might be useful to have a wrapper that returns three columns: divergence, succession, convergence, as defined above. 

Hence I suggest to 

1. Implement new function to calculate succession (time steps n >= 1 allowed) for SE object and add it to colData
2. Implement new wrapper function that adds divergence, succession (n=1), convergence and adds these to colData
3. Consider if we like to have wrappers for calculating divergence and convergence as defined above; this might be useful but not strictly necessary; then we need to reconsider the function namings in mia or miaTime to avoid confusion with `mia::estimateDivergence` which calculates divergence against any reference sample (not just baseline).

**Comment by antagomir** [comment]
Sufficiently implemented now in `getBaselineDivergence`.
