### ISSUE TITLE
Possible new data set on artificial gut vessels

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaTime#19]
The mallard dataset from Silverman et al. (2018) which is provided as a [phyloseq object in fido](https://jsilve24.github.io/fido/articles/non-linear-models.html), and features 4 artificial gut vessels sampled both daily and hourly for 1 month with many technical replicates.

This could provide a clean and well controlled example data set with technical replicates and dense sampling.

To discuss before implementation.

**Comment by microsud** [comment]
This is present in the `microbiomeDatasets`

**Comment by antagomir** [comment]
Ah, super fast!
