### ISSUE TITLE
Issue with temporalMicrobiome20

### ISSUE THREAD

**Issue by microsud** [microbiome/miaTime#40]
The `temporalMicrobiome20 ` dataset seems to be incorrect. The assay has NAs and abundance values are characters not numeric

![image](https://user-images.githubusercontent.com/16476233/168051261-c80dfa7d-8a9d-486b-8023-16a3010c24e6.png)

**Comment by antagomir** [comment]
Thanks! @YagmurSimsekk any comments? Seems that the assay has not been converted into numeric matrix form, can it be fixed?

**Comment by YagmurSimsekk** [comment]
Thanks! @microsud Can you show me the original source of the data? I tried to find it from your repository, but couldn't.

**Comment by microsud** [comment]
I did not create this data ;) This data in part of the `miaTime` in the data-folder.

**Comment by YagmurSimsekk** [comment]
Sorry, I was mistaken by minimalgut data set that was taken from your repository. All good now, thanks :)

**Comment by antagomir** [comment]
Closed via #41
