### ISSUE TITLE
Rethink divergence

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaTime#49]
We have now 
- `mia::estimateDivergence`
- `miaTime::estimateBaselineDivergence`

The latter can replace the former (there is same functionality + more). The latter can do this operation group-wise as well.

However we might also like to define "baseline" per group in arbitrary manner, for instance not just first but also last time point, or anything else. This would support the introduction of a generic function where one can insert group-specific reference samples (calculated separately by the user for instance). This could be just `miaTime::estimateDivergence` for instance, replacing the earlier ones.

Then we can have additional wrappers named
- `miaTime::estimateBaselineDivergence`
- `miaTime::estimateBaselineConvergence`
- etc.

if that seems necessary.

**Comment by TuomasBorman** [comment]
This is already taken into account by commit 4d2ec589dfb597fc1b44e11e52cb1be65de42949. miaTime's divergence functions just add (group-wise) reference samples and `mia::getDivergence()` does the calculation after they have added.
