### ISSUE TITLE
Website for miaTime

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaTime#6]
Create website for `miaTime`, a similar one than in mia and miaViz

**Comment by FelixErnst** [comment]
Have a look at the settings in the pkgdown directories of either package.

**Comment by YagmurSimsekk** [comment]
Thanks for help! It is corrected now

**Comment by antagomir** [comment]
Looks good. Code of conduct header is larger than others, some visual fine tuning could be done but it seems functional now.
