### ISSUE TITLE
getStepwiseDivergence extension to altExp/reducedDims

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaTime#64]
getStepwiseDivergence picks data  from assays; in some use cases it would be useful to apply this to reducedDims (trajectory plots in ordination). 

At the same go, good to consider the use of altExps.

Should be considered more thoughtfully before implementation.

Afterwards, update examples on ordination trajectory plots in miaTime vignettes.

**Comment by antagomir** [comment]
Add same support also for other functions where relevant?

**Comment by antagomir** [comment]
Essentially, in `.check_pairwise_dist` function, recognize if `assay_name` is available in assays or reducedDim. 

Then pick the data from the respective one to the `mat` matrix. Other changes should not be needed in the function itself. Once `mat` has been defined either from assay or altExp, everything should work as expected.


If the same `assay_name` is used in both `assay` and `reducedDim`, then pick it from the `assay` and generate warning that announces this problem.

Update documentation, explaining that `assay_name` can be used also to refer to reducedDim entries. And that assay_name has priority if these two have overlapping names.

Add sufficient unit tests accordingly for the different combinations as this can be a nasty one to catch otherwise-

**Comment by antagomir** [comment]
After done, consider the need to add similar support for `getBaselineDivergence`. Open an issue if relevant.

**Comment by ChouaibB** [comment]
One question about altExp, shall it be an option to choose the assay from as well (along with the option of reducedDim)? or shall altExp be part of the implementation of choosing from assay or reducedDim?
I have a draft of an implementation coming-up with the assay and reducedDim options only so far.

**Comment by antagomir** [comment]
I think (but I am not sure) that reducedDim applies to the full TreeSE object, and is not altExp-specific. Correct if I am mistaken here.

When altExp support is added, the assay should be according to the specified altExp. If altExp is not specified, then the standard assay from TreeSE is used. You could check from other functions in mia how they deal with the altexp argument (for instance runNMDS but perhaps good to check a couple of them in case there are alternative solutions; could even compare to other external packages like scater to make sure the treatments are unified).
