### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by mariamaseng** [microbiome/miaTime#72]
Hi! I would love to explore this awesome package. 
However, trying to download it I get: "There is a binary version available but the source version is later:"

I use code: devtools::install_github("microbiome/miaTime") on r 4.2.2. Any tips for me?

**Comment by mariamaseng** [comment]
It worked now :-)

**Comment by antagomir** [comment]
Great! It has relatively limited number of functions still but all feedback is welcome.
