### ISSUE TITLE
SEtools dependency

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/miaTime#76]
Is there a reason why SEtools::mergeSEs is used instead of mia::mergeSEs https://github.com/microbiome/miaTime/blob/bd56c403cbe1673ae0fb5053f4ddd35b3d0ccf03/R/getStepwiseDivergence.R#L48

I think this should be replaced since it adds additional dependency

**Comment by antagomir** [comment]
This might be just a historical reason.

**Comment by TuomasBorman** [comment]
https://github.com/microbiome/miaViz/pull/75

The issue discussed in PR of miaViz

**Comment by 0xMuluh** [comment]
This has been addressed by @TuomasBorman .
